### ISSUE TITLE
v-analyzer fails to parse wd files containing mutuable variables

### ISSUE THREAD

**Issue by heyimtcn** [vlang/v-analyzer#143]
### Describe the bug

wd: hello.v

hello.v:
```v
fn main() {
    mut foo := 1
}
```

### Expected Behavior

`hello.v` to be parsed

### Current Behavior

at startup it errors, if the error prone statement isn't typed out yet, the moment you type it in (`mut name :=`, at `=`) it errors and closes

### Reproduction Steps

```v
fn main() {
    mut foo := 1
}
```

### Additional Information/Context

os is windows 11

### Environment details (`v doctor` output)

```
OS: windows, Microsoft Windows 11 Pro v26100 64-bit
Processor: 16 cpus, 64bit, little endian, 

getwd: C:\Users\nicof\Documents\Projects\v\hello_world
vexe: C:\v\v.exe
vexe mtime: 2024-11-23 18:02:04

vroot: OK, value: C:\v
VMODULES: OK, value: C:\Users\nicof\.vmodules
VTMP: OK, value: C:\Users\nicof\AppData\Local\Temp\v_0

Git version: git version 2.45.2.windows.1
Git vroot status: weekly.2024.47-22-g2f53e2d2
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,
operable program or batch file.

emcc version: Error: 'emcc' is not recognized as an internal or external command,
operable program or batch file.

thirdparty/tcc: N/A
```

### Editor name

VS Code

### v-analyzer Version

`v-analyzer version 0.0.4-beta.1.e103dbb`

### VS Code Extension Version

`v0.0.5`

**Comment by JalonSolov** [comment]
v-analyzer has a newer version available.  Simplest way to ensure you get the latest is to run this command:
```
v download -RD https://raw.githubusercontent.com/vlang/v-analyzer/main/install.vsh
```
