### ISSUE TITLE
Doc string on function/method is not shown when an annotation is present

### ISSUE THREAD

**Issue by revosw** [vlang/v-analyzer#144]
### Describe the bug

The `read_bytes_into_newlines` looks like this:

```
// read_bytes_into_newline reads from the current position of the file into the provided buffer.
@[deprecated: 'use read_bytes_with_newline instead']
@[deprecated_after: '2024-05-04']
pub fn (f &File) read_bytes_into_newline(mut buf []u8) !int {
	return f.read_bytes_with_newline(mut buf)
}
```

When trying to get the doc comment for the function, the doc does not show up. The problem still persists when you reorder the doc comment and annotations

```
@[deprecated: 'use read_bytes_with_newline instead']
@[deprecated_after: '2024-05-04']
// read_bytes_into_newline reads from the current position of the file into the provided buffer.
pub fn (f &File) read_bytes_into_newline(mut buf []u8) !int {
	return f.read_bytes_with_newline(mut buf)
}
```

When removing the annotations entirely, the comment shows up in intellisense

### Expected Behavior

The doc comment shows up in intellisense and on hover

### Current Behavior

The doc comment is not shown at all

### Reproduction Steps

1. Open a new project
2. Create a new `File` instance
3. Call `read_bytes_into_newlines` on the file instance
4. Try to hover the cursor, or ctrl+space to show intellisense. The doc comment does not show

### Environment details (`v doctor` output)

V full version: V 0.4.8 3108820.6f4c59e
OS: windows, Microsoft Windows 11 Pro v22631 64-bit
Processor: 12 cpus, 64bit, little endian, 

getwd: C:\dev\v\winmd
vexe: C:\dev\_tools\v\v.exe
vexe mtime: 2024-11-30 22:27:08

vroot: OK, value: C:\dev\_tools\v
VMODULES: OK, value: C:\Users\simen\.vmodules
VTMP: OK, value: C:\Users\simen\AppData\Local\Temp\v_0

Git version: git version 2.40.0.windows.1
Git vroot status: weekly.2024.48-25-g6f4c59e0
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,
operable program or batch file.

emcc version: Error: 'emcc' is not recognized as an internal or external command,
operable program or batch file.

thirdparty/tcc status: thirdparty-windows-amd64 b425ac82

### Editor name

Visual Studio Code

### v-analyzer Version

0.0.1-beta-1

### VS Code Extension Version

0.0.5

**Comment by JalonSolov** [comment]
Try updating your v-analyzer.  The current version is 0.0.5.  0.0.1-beta-1 is.. ancient, in comparison.

The simplest way to update, as shown on the v-analyzer home page, is by running
```
v download -RD https://raw.githubusercontent.com/vlang/v-analyzer/main/install.vsh
```

**Comment by revosw** [comment]
After running the command, I still get `0.0.1-beta-1`. I'm guessing that's the server language version, while 0.0.5 is the version of the client extension that talks to the language server

**Comment by JalonSolov** [comment]
```
$ bin/v-analyzer -v
v-analyzer version 0.0.5.4d65c78
$
```

**Comment by revosw** [comment]
Alright, so I had to completely uninstall v-analyzer by deleting `%USERPROFILE%\.config\v-analyzer` then reinstalling using the `v download` command mentioned above. Now it's properly updated, and the doc comment shows!
> v-analyzer version: 0.0.5.ef4243a
