### ISSUE TITLE
`os.args` is not found by v-analyzer and the type is shown as `unknown`

### ISSUE THREAD

**Issue by nikeedev** [vlang/v-analyzer#28]
### Describe the bug

This image tells it
![image](https://github.com/vlang/v-analyzer/assets/69197950/362a7130-c8b7-4e1e-930c-2cedd9b91476)

and also isnt showing it when looking it up, only `args_after` and `args_before`:
![image](https://github.com/vlang/v-analyzer/assets/69197950/81045be6-a70b-4732-a055-2495b47b0759)

### Expected Behavior

Well i expected it to be showing `os.args` and also showing that it gives not `unknown` but `[]string`

### Current Behavior

Well the image above explain it mostly.

### Reproduction Steps

Write `os.args`, and wait for autocompletion to recommend it, if you have that issue, os.args would not appear on the list of recommendations for completion.

### Possible Solution

I don't have any solutions or fixes, but it probably also lies in with the info about variables and that v-analyzer doesnt recogonize/use them as a part of the completion.

### Environment details (`v doctor` output)

V full version: V 0.4.4 c024721.eaa4edf
OS: windows, Microsoft Windows 11 Pro Education v22631 64-bit
Processor: 12 cpus, 64bit, little endian,

getwd: D:\
vexe: D:\apps\v\v.exe
vexe mtime: 2024-03-15 12:10:00

vroot: OK, value: D:\apps\v
VMODULES: OK, value: C:\Users\myftr\.vmodules
VTMP: OK, value: C:\Users\myftr\AppData\Local\Temp\v_0

Git version: git version 2.43.0.windows.1
Git vroot status: weekly.2023.43-1000-geaa4edf4 (3 commit(s) behind V master)
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,
operable program or batch file.

thirdparty/tcc status: thirdparty-windows-amd64 b99a453d

### Editor name

Visual Studio Code

### v-analyzer Version

v-analyzer version 0.0.4-beta.1.be121f7, supposed to be the latest

### VS Code Extension Version

v0.0.2

**Comment by bramvbilsen** [comment]
I think this is related to https://github.com/vlang/v-analyzer/issues/23
