### ISSUE TITLE
Failed to build v-analyzer on Android 

### ISSUE THREAD

**Issue by NikhilTomar3000** [vlang/v-analyzer#94]
### Describe the bug

I tried to update v-analyzer in Termux but the version does not change instead an error is thrown that it failed to build v-analyzer.

### Expected Behavior

Update v-analyzer to latest version.

### Current Behavior

Error
![Screenshot_2024-04-13-19-37-22-36_84d3000e3f4017145260f7618db1d683](https://github.com/vlang/v-analyzer/assets/55707957/671bed31-372f-4e5e-bac5-7186671936c0)

### Reproduction Steps

Open Termux and type "v-analyzer up".

### Environment details (`v doctor` output)

V full version: V 0.4.5 294f7e4.96751ed                           OS: termux, 4.19.157-perf+, #1 SMP PREEMPT Wed Mar 13 12:45:10 CST 2024
Processor: 8 cpus, 64bit, little endian

getwd: /data/data/com.termux/files/home
vexe: /data/data/com.termux/files/home/v-git/v
vexe mtime: 2024-04-13 13:52:25

vroot: OK, value: /data/data/com.termux/files/home/v-git
VMODULES: OK, value: /data/data/com.termux/files/home/.vmodules
VTMP: OK, value: /data/data/com.termux/files/usr/tmp/v_10310

Git version: git version 2.44.0
Git vroot status: weekly.2023.42-1225-g96751ede
.git/config present: true

CC version: clang version 18.1.3
thirdparty/tcc status: thirdparty-unknown-unknown de82a130

### Editor name

Not applicable 

### v-analyzer Version

v-analyzer version 0.0.1-beta.1

**Comment by ttytm** [comment]
Hey @NikhilTomar3000,

Sorry about the inconvenience. 
The v-analyzer version you are using still refers to the old v-analyzer repository.

![Screenshot_20240414_065236](https://github.com/vlang/v-analyzer/assets/34311583/5a8901d9-8553-4c7d-a496-535bfb94ffd6)

`v-analyzer/v-analyzer` moved to an official vlang repository at `vlang/v-analyzer`.

More fixes to the update processes have been made recently and will be available in release version soon. So what I can recommend for now is to re-install the nightly version from this repository, then keeping up to date with the latest nightly versions should work for you.

**Comment by NikhilTomar3000** [comment]
> Hey @NikhilTomar3000,
> 
> Sorry about the inconvenience. 
> The v-analyzer version you are using still refers to the old v-analyzer repository.
> 
> ![Screenshot_20240414_065236](https://github.com/vlang/v-analyzer/assets/34311583/5a8901d9-8553-4c7d-a496-535bfb94ffd6)
> 
> `v-analyzer/v-analyzer` moved to an official vlang repository at `vlang/v-analyzer`.
> 
> More fixes to the update processes have been made recently and will be available in a release version soon. So what I can recommend for now is to re-install the nightly version from this repository, then keeping up to date with the latest nightly versions should work for you.

Thank you. Reinstalling worked after changing the repo url. I think it should be indicated in the older repo's readme that it has been moved here. Also, it should still have been updated to 0.0.3-beta.1 from 0.0.1-beta.1. Again, thank you 'cause I really didn't pay attention to the repo url and ended up using the one I earlier used to install v-analyzer.

**Comment by ttytm** [comment]
Your welcome.
Afaik the old repo is considered read only at that point.
